language: python

sudo: false

python:
- "3.6"

env:
  global:
    - AWS_REGION=eu-central-1

cache: pip

install:
  - pip install pipenv
  - pipenv sync

deploy:
  - provider: script
    skip_cleanup: true
    script: cd app && pipenv run zappa update && pipenv run ./manage.py collectstatic --noinput && pipenv run zappa manage dev "migrate"
    on:
      branch: master