language: python
sudo: false
python:
- '3.6'
env:
  global:
  - AWS_REGION=eu-central-1
  - S3_BUCKET_NAME=newsforyou-static-staging
  - SECRET_KEY=a
  - BOT_SERVICE_ENDPOINT=https://example.com/
cache: pip
install:
- pip install pipenv
- pipenv sync --dev
script:
- echo "No tests :)"
deploy:
- provider: script
  skip_cleanup: true
  script: cd app && zappa update staging && zappa manage staging "migrate" && ./manage.py
    collectstatic --noinput
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: cd app && zappa update prod && zappa manage prod "migrate" && ./manage.py
    collectstatic --noinput
  on:
    branch: production
notifications:
  slack:
    secure: k04gHLr2jCikDDkxgh3XIOMS4h+f7OL4Gnao1LpueSFYmL19qp5q9gvtIpMPz7u5yGWQarD/FNoH5xM6Crm/4BLIDYYZtezaSEoRUGGqlGrx4ViTXCUVAlrV3V+8T+4KSJ4lzE0iwY0V3BrqyITHzyURnv3P5TirtyXQnf+HqUKd7AJqPPKswxGpSXVGXOkslzyz+qQsF6rGM31wF7W1fBnzhTmeDtWOlDglKSRnWhInDXfhdUCiEs4un0bmmlNFSo4vtCqa1FTlxbYJxosRFfQ3I1+ozFLdXzhFMjORq0HKjPYz7lygg/SZmEGq8hX/hfzjhi4LFIF3v0KVsmuheXiZeGDZvLn2OgvFC9SoSUSYmZyOW6SFnm5Xm2RCTCV01jYw9t0jY/wyu5dO6upNrEJh+tH5hzclQ/DUspWviAADpH9XQbf3od2U4fIDK3+ZuwXjAxiRg7luB5JRndGScOkcCsulrBzkwlvwPUmanWYDNIehYFmAydrqqZQnRql4LEYRROT5YghY/fCN1cGTNdB4wyPIxsSy2VNypsaHarWfd3UJzwqRHyGvOPub0qAtC9fqeaXrL06AWTCrA6YF4uNWF2EqGFaZ3FutA+IO/rKeu/0JFy7J+r2F2PDrowRCXAiqk1hgynba9+ZJzZTdRqGooxUwZwVhkFXlJ2FC4YY=
    on_pull_requests: false
    template:
      - "Deployment %{result}:"
      - "<%{compare_url}|%{repository_slug}:%{branch}#%{commit}> by %{author}"