# Generated by Django 2.1.2 on 2018-10-09 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Titel')),
                ('text', models.CharField(help_text='Hier die Meldung auf Deutsch eingeben. Die Übersetzung zu anderen Sprachen wird weiter unten eingegeben, falls nötig.', max_length=640, verbose_name='Text Deutsch')),
                ('arabic', models.BooleanField(blank=True, default=False, verbose_name='Arabisch')),
                ('persian', models.BooleanField(blank=True, default=False, verbose_name='Persisch')),
                ('english', models.BooleanField(blank=True, default=False, verbose_name='Englisch')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt')),
                ('published', models.BooleanField(default=False, help_text='Solange dieser Haken nicht gesetzt ist, wird diese Meldung nicht versendet.', verbose_name='Freigegeben')),
                ('delivered', models.BooleanField(default=False, verbose_name='Versendet')),
            ],
            options={
                'verbose_name': 'Meldung',
                'verbose_name_plural': 'Meldungen',
                'ordering': ['-created'],
            },
        ),
    ]
