# Generated by Django 2.1.2 on 2018-10-09 14:55
from enum import Enum

import cms.models.translations
from django.db import migrations, models
import django.db.models.deletion


class Language(Enum):
    ARABIC = 'arabic'
    PERSIAN = 'persian'
    ENGLISH = 'english'

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(Language('arabic'), 'arabic'), (Language('persian'), 'persian'), (Language('english'), 'english')], max_length=640, verbose_name='Sprache')),
                ('text', models.CharField(max_length=640, verbose_name='Text Übersetzung')),
            ],
            options={
                'verbose_name': 'Meldungs-Übersetzung',
                'verbose_name_plural': 'Meldungs-Übersetzung',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='report',
            name='german',
            field=models.BooleanField(blank=True, default=False, verbose_name='Deutsch'),
        ),
        migrations.AddField(
            model_name='reporttranslation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', related_query_name='translation', to='cms.Report'),
        ),
    ]
