# Generated by Django 2.1.2 on 2018-11-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20181030_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttranslation',
            name='link',
            field=models.CharField(blank=True, help_text='Hier eine Link-URL eintragen, wird als Button an die Push-Nachricht angehängt.', max_length=1024, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.CharField(help_text='Hier die Meldung auf Deutsch eingeben. Die Übersetzung zu anderen Sprachen wird weiter unten eingegeben, falls nötig.', max_length=628, verbose_name='Text Deutsch'),
        ),
        migrations.AlterField(
            model_name='reporttranslation',
            name='text',
            field=models.CharField(max_length=628, verbose_name='Text Übersetzung'),
        ),
    ]
