# Generated by Django 2.1.3 on 2018-11-15 11:35

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20181114_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='media_original',
            field=s3direct.fields.S3DirectField(blank=True, null=True, verbose_name='Medien-Anhang'),
        ),
        migrations.AlterField(
            model_name='reporttranslation',
            name='media_original',
            field=s3direct.fields.S3DirectField(blank=True, null=True, verbose_name='Medien-Anhang'),
        ),
    ]
