# Generated by Django 2.1.3 on 2018-12-05 14:04

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20181205_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_original', s3direct.fields.S3DirectField(blank=True, null=True, verbose_name='Medien-Anhang')),
                ('media_note', models.CharField(blank=True, help_text='Bei Foto-Anhang hier die Quelle eintragen. Wird auf dem Foto angezeigt.', max_length=100, null=True, verbose_name='Credit')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Verarbeitet')),
                ('name', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('text', models.CharField(max_length=640, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='FAQFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_original', s3direct.fields.S3DirectField(blank=True, null=True, verbose_name='Medien-Anhang')),
                ('media_note', models.CharField(blank=True, help_text='Bei Foto-Anhang hier die Quelle eintragen. Wird auf dem Foto angezeigt.', max_length=100, null=True, verbose_name='Credit')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Verarbeitet')),
                ('question', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frage')),
                ('text', models.CharField(max_length=640, verbose_name='Text')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', related_query_name='fragment', to='cms.FAQ')),
            ],
            options={
                'verbose_name': 'FAQ-Fragment',
                'verbose_name_plural': 'FAQ-Fragmente',
                'ordering': ('id',),
            },
        ),
    ]
