# Generated by Django 2.1.3 on 2018-12-06 17:00

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20181205_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='FAQFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_original', s3direct.fields.S3DirectField(blank=True, null=True, verbose_name='Medien-Anhang')),
                ('media_note', models.CharField(blank=True, help_text='Bei Foto-Anhang hier die Quelle eintragen. Wird auf dem Foto angezeigt.', max_length=100, null=True, verbose_name='Credit')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Verarbeitet')),
                ('text', models.CharField(max_length=640, verbose_name='Chat-Bubble')),
            ],
            options={
                'verbose_name': 'FAQ-Fragment',
                'verbose_name_plural': 'FAQ-Fragmente',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FAQ Übersetzung',
                'verbose_name_plural': 'FAQ Übersetzungen',
            },
        ),
        migrations.AddField(
            model_name='faqfragment',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='cms.FAQTranslation', verbose_name='FAQ Übersetzung'),
        ),
        migrations.AddField(
            model_name='faq',
            name='arabic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arabic_faqs', to='cms.FAQTranslation', verbose_name='Text Arabisch'),
        ),
        migrations.AddField(
            model_name='faq',
            name='english',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='english_faqs', to='cms.FAQTranslation', verbose_name='Text Englisch'),
        ),
        migrations.AddField(
            model_name='faq',
            name='german',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='german_faqs', to='cms.FAQTranslation', verbose_name='Text Deutsch'),
        ),
        migrations.AddField(
            model_name='faq',
            name='persian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persian_faqs', to='cms.FAQTranslation', verbose_name='Text Persisch'),
        ),
    ]
