# Generated by Django 2.1.3 on 2018-12-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20181206_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='slug',
        ),
        migrations.AddField(
            model_name='faq',
            name='handle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Handle'),
        ),
    ]
