# Generated by Django 2.1.7 on 2019-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20181207_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttranslation',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Versendet'),
        ),
        migrations.AddField(
            model_name='reporttranslation',
            name='published',
            field=models.BooleanField(default=False, help_text='Solange dieser Haken nicht gesetzt ist, wird diese Meldung nicht versendet.', verbose_name='Freigegeben'),
        ),
    ]
