# Generated by Django 2.1.7 on 2019-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190508_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='published',
            field=models.BooleanField(default=False, help_text='Solange dieser Haken nicht gesetzt ist, wird diese Meldung nicht versendet und/oder angezeigt.', verbose_name='Freigegeben'),
        ),
        migrations.AlterField(
            model_name='reporttranslation',
            name='published',
            field=models.BooleanField(default=False, help_text='Solange dieser Haken nicht gesetzt ist, wird diese Übersetzung nicht versendet und/oder angezeigt.', verbose_name='Freigegeben'),
        ),
    ]
